services:
  rstudio:
    image: rstudio-server-scrnaseq:1.2
    ports:
      - "8080:8787"
    environment:
      - PASSWORD=single_cell
      - ROOT=TRUE
      - GROUPID=1001
      - USERID=1004
    volumes:
      - type: "bind"
        source: "/media/data/NGS/Projects/scrnaseq-clonal2"
        target: "/home/rstudio/scrnaseq-clonal2"
    restart: always
