---
title: "cycle 4 - MCL cells"
output: 
  html_notebook:
    toc: true
    toc_float: true
    code_folding: show
    theme: united
---

```{r setup}
library(tidyverse)
library(cowplot)
library(openxlsx)

# SC methods
library(scran)
library(scater)
library(bluster)
library(Seurat)

# Annotations
library(SingleR)
library(tricycle)

# Variable with random seed value used throughout the analysis for reproducibility
random_seed_value = 17

# Parallelization
library(BiocParallel)
bpp <- MulticoreParam()

# Path to project folder
wd <- "/media/data/NGS/Projects/scrnaseq-clonal2/"
source(file.path(wd, "scRNAseq/analysis/scripts/colors.R"))

iteration_input = "4_all_cells_labbeled"
sce.dir <- file.path(wd, "scRNAseq/analysis/outputs", iteration_input)
```

```{r}
patients <- c("P009", "P022", "P027", "P087", "P069")
timepoints <- c("DG", "REL")
compartments <- c("PBMC", "BM", "LN", "TON", "GUT", "ASC")

samples.df <- read.xlsx(file.path(sce.dir, "cell_metadata.xlsx")) %>% 
  mutate(
    patient = factor(patient, levels = patients),
    timepoint = factor(timepoint, levels = timepoints),
    compartment = factor(compartment, levels = compartments)
  )
samples.df
```

```{r}
sce <- readRDS(file = file.path(sce.dir, "sce.rds"))
sce
```

```{r}
sce %>% colData() %>% as.data.frame()
```

```{r}
sce.to.seu <- sce
rownames(sce.to.seu) <- make.unique(rowData(sce.to.seu)[["Symbol"]])
seu <-
  SeuratObject::as.Seurat(sce.to.seu, counts = "counts", data = "logcounts")

rowData(sce.to.seu)[["Symbol"]]

```

