---
title: "`r params$sample_id` - Seurat analysis and clustering"
output:
  html_notebook:
    code_folding: hide
params:
  sample_id: "P009_DG"
  path_sce_input: "/media/data/NGS/Projects/MCL-scrnaseq-phanthomMenace/scrnaxus/results/P009_DG/cell_QC/P009_DG_cells.sce"
  path_sce_output: "test_sce.rds"
  FindVariableFeatures_nfeatures: 2000
  RunPCA_npcs: 30
  FindNeighbors_k: 30
  FindClusters_res: 0.5
  seed: 42
---

```{r setup}
sample_id <- params$sample_id
path_sce_input <- params$path_sce_input
path_sce_output <- params$path_sce_output

# Seurat parameters
FindVariableFeatures_nfeatures <- params$FindVariableFeatures_nfeatures
RunPCA_npcs <- params$RunPCA_npcs
FindNeighbors_k <- params$FindNeighbors_k
FindClusters_res <- params$FindClusters_res

seed <- params$seed
set.seed(seed)

# Load the libraries
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(Seurat)
  library(scater)
  library(scran)
  library(patchwork)
})
```

# Read the sce

```{r load_sce}
sce <- readRDS(path_sce_input)
sce
```

# Seurat processing

```{r seurat_conversion}
seurat <- as.Seurat(sce, counts = "counts", data = NULL)
seurat
```

```{r normalization}
seurat <- NormalizeData(seurat,
                        normalization.method = "LogNormalize",
                        scale.factor = 10000)
```

```{r variable_features}
seurat <- FindVariableFeatures(
  seurat,
  selection.method = "vst",
  loess.span = 0.3,
  nfeatures = FindVariableFeatures_nfeatures
)
```

```{r vst_plot}
top10 <- head(VariableFeatures(seurat), 10)

vst_plot <- VariableFeaturePlot(seurat)
vst_plot <- LabelPoints(plot = vst_plot, points = top10, repel = TRUE)
vst_plot
```

```{r scaling}
seurat <- ScaleData(seurat, model.use = "linear")
```

```{r PCA}
seurat <- RunPCA(seurat, seed.use = seed, npcs = RunPCA_npcs, seed.use = seed)
```

```{r elbow_plot}
ElbowPlot(seurat)
```


```{r UMAP}
seurat <- RunUMAP(seurat, reduction = "pca", dims = 1:20)
```


```{r clustering}
seurat <- FindNeighbors(
  seurat,
  k.param = FindNeighbors_knn,
  reduction = "pca",
  dims = 1:20
)
seurat <- FindClusters(seurat,
                       resolution = FindClusters_res)
```

```{r transfer_results_to_sce}
# Normalization
assay(sce, "logcounts", withDimnames = FALSE) <- GetAssayData(seurat, layer = "data", assay = "originalexp")

# VST
rowData_vst <- seurat@assays$originalexp@meta.features
if(all(rowData_vst[["ID"]] == rowData(sce)[["ID"]])){
  rowData(sce)[["vst.variance.standardized"]] <- rowData_vst[["vst.variance.standardized"]]
  rowData(sce)[["vst.variable"]] <- rowData_vst[["vst.variable"]]
} else {
  stop("Variable features do not match!")
}

# PCA
reducedDims(sce)[["PCA"]] <- Embeddings(seurat, reduction = "pca")
attr(reducedDims(sce)[["PCA"]], "rotation") <- Loadings(seurat, reduction = "pca")
pca_variance <- seurat@reductions$pca@stdev^2
attr(reducedDims(sce)[["PCA"]], "percentVar") <- pca_variance / sum(pca_variance) * 100

# UMAP
reducedDims(sce)[["UMAP"]] <- Embeddings(seurat, reduction = "umap")

# clusters
sce[["clusters"]] <- seurat$seurat_clusters

sce
```


```{r UMAP_plot, fig.width=5.5, fig.height=5}
plotUMAP(sce,
         color_by = "clusters",
         text_by = "clusters")
```

# Write resulting sce

```{r print_sce}
sce
```

```{r write_sce}
saveRDS(sce, path_sce_output)
```

# Session info

```{r sessionInfo}
print(sessionInfo())
```

```{r gc}
gc()
```
