---
title: "R Notebook"
output: html_notebook
---

```{r setup}
library(tidyverse)
library(openxlsx)

random_seed_value = 17

wd <- here::here()
source(file.path(wd, "scRNAseq/analysis/scripts/colors.R"))
source(file.path(wd, "scRNAseq/analysis/scripts/setup.R"))

iteration_input = "6_MCL_CNV"
sce.dir <- file.path(wd, "scRNAseq/analysis/outputs", iteration_input)

figures.out.dir <- file.path(wd, "scRNAseq/figures")
tables.out.dir <- file.path(wd, "scRNAseq/analysis/results/DE_analysis_DK")
```

```{r}
sce <- readRDS(file.path(sce.dir, "sce.rds"))
colnames_to_store <- colData(sce) %>%
  as.data.frame() %>%
  dplyr::select(
    -contains("subsets_"),
    -contains("top_"),
    -contains("has_"),
    -contains("proportion_")
  ) %>%
  colnames()
colData(sce) <- colData(sce)[colnames_to_store]
sce
```

```{r}
CNV.clones <- colData(sce) %>% 
  as.data.frame() %>% 
  remove_rownames() %>% 
  select(CNV.group, CNV.clone) %>% 
  distinct() %>% 
  arrange(CNV.group) %>% 
  filter(CNV.clone != "REL")
CNV.clones
```

```{r}
CNV.clones.counts <- colData(sce) %>% 
  as.data.frame() %>% 
  remove_rownames() %>% 
  select(patient, timepoint, CNV.group, CNV.clone) %>% 
  group_by(patient, timepoint, CNV.group) %>% 
  reframe(n = n()) %>% 
  pivot_wider(names_from = timepoint, values_from = n, values_fill = 0) %>% 
  left_join(
    ., CNV.clones, by = "CNV.group"
  ) %>% 
  select(patient, CNV.group, CNV.clone, DG, REL) %>% 
  mutate(
    CNV.group = word(CNV.group, 2, sep = "\\."),
    CNV.group = as.numeric(CNV.group)
  ) %>% 
  arrange(patient, CNV.clone, CNV.group)
CNV.clones.counts
```

```{r}
write.xlsx(
  CNV.clones.counts,
  file = file.path(tables.out.dir, "CNVclones_counts.xlsx")
)
```












