---
title: "R Notebook"
output: html_notebook
---

```{r setup}
library(tidyverse)
library(ComplexHeatmap)

library(scran)
library(scater)

# Parallelization
library(BiocParallel)
bpp <- MulticoreParam(workers = 16)

random_seed_value = 17

wd <- here::here()
source(file.path(wd, "scRNAseq/analysis/scripts/colors.R"))
source(file.path(wd, "scRNAseq/analysis/scripts/setup.R"))

iteration_input = "6_MCL_CNV"
sce.dir <- file.path(wd, "scRNAseq/analysis/outputs", iteration_input)
```

```{r}
sce <- readRDS(file.path(sce.dir, "sce.rds"))
colnames_to_store <- colData(sce) %>%
  as.data.frame() %>%
  select(
    -contains("subsets_"),
    -contains("top_"),
    -contains("has_"),
    -contains("proportion_")
  ) %>%
  colnames()
colData(sce) <- colData(sce)[colnames_to_store]
sce
```

```{r, fig.width=7, fig.height=2.5}
plotReducedDim(sce, dimred = "TSNE_corrected_SamplePhase",
               color_by = "CNV.clone",
               other_fields = c("CNV.clone")
               ) +
  facet_grid(~ CNV.clone) +
  theme_bw()
```


```{r, fig.width=10, fig.height=6}
plotReducedDim(sce, dimred = "TSNE_corrected_SamplePhase",
               color_by = "CNV.clone",
               other_fields = c("patient", "CNV.clone")
               ) +
  facet_grid(CNV.clone ~ patient) +
  theme_bw()
```

```{r}
sce.DG <- sce[, sce$timepoint == "DG"]
sce.DG$CNV.clone <- factor(sce.DG$CNV.clone, levels = c("DGex", "DGs"))
unique(sce.DG$CNV.clone)
```

## `scoreMarkers` for each patient separately

```{r}
DGs.markers.list <- list()
for(patient in c("P009", "P022", "P027", "P087", "P069")){
  sce.patient <- sce.DG[, sce.DG$patient == patient]
  markers <- scoreMarkers(sce.patient,
                          groups = sce.patient$CNV.clone,
                          pairings = c("DGs", "DGex"),
                          lfc = 0.5,
                          BPPARAM = bpp
                          )
  rm(sce.patient)
  DGs.markers.list[[patient]] <- markers[["DGs"]] %>% 
    as.data.frame() %>% 
    rownames_to_column("genename") %>% 
    arrange(desc(mean.AUC))
}
lapply(DGs.markers.list, head, 20)
```

```{r, fig.width=4, fig.height=7}
patient = "P009"

genes.to.plot <- DGs.markers.list[[patient]] %>% 
  arrange(desc(mean.AUC)) %>% 
  head(100) %>% pull(genename)

plotGroupedHeatmap(
    sce,
    features = genes.to.plot,
    group = "CNV.clone",
    center = TRUE,
    main = patient,
    fontsize_row = 0.0001,
    # zlim = c(-0.5, 0.5),
    cluster_rows = T
  )
```

```{r, fig.width=4, fig.height=7}
patient = "P022"

genes.to.plot <- DGs.markers.list[[patient]] %>% 
  arrange(desc(mean.AUC)) %>% 
  head(100) %>% pull(genename)

plotGroupedHeatmap(
    sce,
    features = genes.to.plot,
    group = "CNV.clone",
    center = TRUE,
    main = patient,
    fontsize_row = 0.0001,
    # zlim = c(-0.5, 0.5),
    cluster_rows = T
  )
```

```{r, fig.width=4, fig.height=7}
patient = "P027"

genes.to.plot <- DGs.markers.list[[patient]] %>% 
  arrange(desc(mean.AUC)) %>% 
  head(100) %>% pull(genename)

plotGroupedHeatmap(
    sce,
    features = genes.to.plot,
    group = "CNV.clone",
    center = TRUE,
    main = patient,
    fontsize_row = 0.0001,
    # zlim = c(-0.5, 0.5),
    cluster_rows = T
  )
```

```{r, fig.width=4, fig.height=7}
patient = "P087"

genes.to.plot <- DGs.markers.list[[patient]] %>% 
  arrange(desc(mean.AUC)) %>% 
  head(100) %>% pull(genename)

plotGroupedHeatmap(
    sce,
    features = genes.to.plot,
    group = "CNV.clone",
    center = TRUE,
    main = patient,
    fontsize_row = 0.001,
    # zlim = c(-0.5, 0.5),
    cluster_rows = T
  )
```

```{r}
patient = "P009"

DGs.markers.list[[patient]] %>% 
  arrange(desc(mean.AUC)) %>% 
  select("genename", "mean.AUC", "rank.AUC")
```

```{r}
library(ReactomePA)
library(org.Hs.eg.db)  # Assuming human data
library(AnnotationDbi)
```

```{r}
GSE.list <- list()
for (patient in c("P009", "P022", "P027", "P087")) {
  markers <- DGs.markers.list[[patient]] %>%
    arrange(desc(mean.AUC)) %>%
    dplyr::select("genename", "mean.AUC")
  entrez_ids <- mapIds(
    org.Hs.eg.db,
    keys = markers$genename,
    column = "ENTREZID",
    keytype = "SYMBOL",
    multiVals = "first"
  )
  valid_indices <- which(!is.na(entrez_ids))
  
  gene_list <- markers$mean.AUC[valid_indices]
  names(gene_list) <- entrez_ids[valid_indices]
  
  GSE.list[[patient]] <- gsePathway(
    geneList = gene_list,
    organism = "human",
    minGSSize = 10,
    pvalueCutoff = 0.01,
    verbose = F
  ) %>%
    as.data.frame()
}
GSE.list
```

```{r, fig.width=8, fig.height=6}
GSE.plots.list <- list()
for (patient in names(GSE.list)) {
  GSE.plots.list[[patient]] <- GSE.list[[patient]] %>%
    mutate(GeneCount = str_count(core_enrichment, "/") + 1,
           GeneRatio = GeneCount / setSize) %>%
    arrange(desc(GeneRatio)) %>%
    filter(abs(NES) > 1.2 & GeneRatio > 0.5) %>%
    mutate(Description = factor(Description, levels = rev(.$Description))) %>%
    head(20) %>%
    ggplot(aes(x = GeneRatio, y = Description)) +
    geom_point(shape = 21, aes(fill = NES, size = GeneCount)) +
    scale_fill_gradient2(name = "NES",
                         low = "blue",
                         high = "red") +
    scale_x_continuous(labels = scales::percent) +
    theme_bw(base_size = 14) + labs(y = NULL) +
    ggtitle(patient)
}
GSE.plots.list
```






## Wilcoxon test for DGs vs DGex

### All patients

```{r}
set.seed(random_seed_value)
wilcox.subclones <- pairwiseWilcox(sce.DG, lfc = 0.5,
                                   groups = sce.DG$CNV.clone,
                                   BPPARAM = bpp
                                   )
wilcox.DG.subclones <- wilcox.subclones$statistics[[2]] %>% 
  as.data.frame() %>% 
  rownames_to_column("genesymbol") %>% 
  filter(p.value < 0.05 & FDR < 0.05) %>% 
  arrange(AUC)
wilcox.DG.subclones
```

```{r, fig.width=5, fig.height=8}
genes.to.plot <- wilcox.DG.subclones$genesymbol

plotGroupedHeatmap(
    sce,
    features = genes.to.plot,
    group = "CNV.clone",
    center = TRUE,
    main = "",
    fontsize_row = 10,
    # zlim = c(-0.5, 0.5),
    cluster_rows = T
  )
```

### All aggressive patients

```{r}
set.seed(random_seed_value)
sce.DG.aggr <- sce.DG[, sce.DG$patient %in% c("P009", "P022", "P027", "P087")]

wilcox.subclones.aggr <- pairwiseWilcox(
  sce.DG.aggr,
  lfc = 0.5,
  groups = sce.DG.aggr$CNV.clone,
  BPPARAM = bpp
)
wilcox.DG.subclones.aggr <- wilcox.subclones.aggr$statistics[[2]] %>%
  as.data.frame() %>%
  rownames_to_column("genesymbol")

wilcox.DG.subclones.aggr.sig <- wilcox.DG.subclones.aggr %>% 
  filter(p.value < 0.05 & FDR < 0.05) %>%
  arrange(AUC)
wilcox.DG.subclones.aggr.sig
```

```{r, fig.width=5, fig.height=5}
genes.to.plot <- wilcox.DG.subclones.aggr.sig$genesymbol

plotGroupedHeatmap(
    sce,
    features = genes.to.plot,
    group = "CNV.clone",
    center = TRUE,
    main = "",
    fontsize_row = 10,
    # zlim = c(-0.5, 0.5),
    cluster_rows = T
  )
```

### Separately by patient

```{r}
wilcox.test.results <- list()
wilcox.test.results.sig <- list()
for (patient in c("P009", "P022", "P027", "P087", "P069")) {
  sce.patient <- sce.DG[, sce.DG$patient == patient]
  
  set.seed(random_seed_value)
  test <- pairwiseWilcox(
    sce.patient,
    lfc = 0.5,
    groups = sce.patient$CNV.clone,
    BPPARAM = bpp
  )
  wilcox.test.results[[patient]] <- test$statistics[[2]] %>%
    as.data.frame() %>%
    rownames_to_column("genesymbol") %>%
    arrange(AUC)
  
  results.sig <- wilcox.test.results[[patient]] %>%
    filter(p.value < 0.05 & FDR < 0.05)
  
  if (dim(results.sig)[1] > 0) {
    wilcox.test.results.sig[[patient]] <- results.sig
  }
}
wilcox.test.results.sig
```

```{r, fig.width=4, fig.height=4}
patient <- "P009"

genes.to.plot <- wilcox.test.results.sig[[patient]]$genesymbol
plotGroupedHeatmap(
    sce,
    features = genes.to.plot,
    group = "CNV.clone",
    center = TRUE,
    main = patient,
    fontsize_row = 10,
    cluster_rows = T
  )
```

```{r, fig.width=4, fig.height=8}
patient <- "P022"

genes.to.plot <- wilcox.test.results.sig[[patient]]$genesymbol
plotGroupedHeatmap(
    sce,
    features = genes.to.plot,
    group = "CNV.clone",
    center = TRUE,
    main = patient,
    fontsize_row = 10,
    cluster_rows = T
  )
```

```{r, fig.width=4, fig.height=8}
patient <- "P087"

genes.to.plot <- wilcox.test.results.sig[[patient]]$genesymbol
plotGroupedHeatmap(
    sce,
    features = genes.to.plot,
    group = "CNV.clone",
    center = TRUE,
    main = patient,
    fontsize_row = 10,
    cluster_rows = T
  )
```

## Pairwise t-tests

### For all patients

```{r}
set.seed(random_seed_value)
Ttest.subclones <- pairwiseTTests(sce.DG,
                                  lfc = 0.5,
                                  groups = sce.DG$CNV.clone,
                                  BPPARAM = bpp)
Ttest.subclones$statistics[[2]] %>%
  as.data.frame() %>%
  filter(p.value < 0.05 & FDR < 0.05) %>%
  arrange(logFC)
```

### All aggressive patients

```{r}
set.seed(random_seed_value)
sce.DG.aggr <- sce.DG[, sce.DG$patient %in% c("P009", "P022", "P027", "P087")]
set.seed(random_seed_value)
Ttest.subclones.aggr <- pairwiseTTests(
  sce.DG.aggr,
  lfc = 0.5,
  groups = sce.DG.aggr$CNV.clone,
  BPPARAM = bpp
)
Ttest.subclones.aggr$statistics[[2]] %>%
  as.data.frame() %>%
  filter(p.value < 0.05 & FDR < 0.05) %>%
  arrange(logFC)
```

### For each patient separately

```{r}
Ttest.results.full <- list()
Ttest.results.sig <- list()
for (patient in c("P009", "P022", "P027", "P087", "P069")) {
  sce.patient <- sce.DG[, sce.DG$patient == patient]
  
  set.seed(random_seed_value)
  test <- pairwiseTTests(
    sce.patient,
    lfc = 0.5,
    groups = sce.patient$CNV.clone,
    BPPARAM = bpp
  )
  Ttest.results.full[[patient]] <- test$statistics[[2]] %>%
    as.data.frame() %>%
    rownames_to_column("genesymbol")
  
  Ttest.results.sig[[patient]] <- Ttest.results.full[[patient]] %>% 
    filter(p.value < 0.05 & FDR < 0.05) %>%
    arrange(logFC)
}
Ttest.results.sig
```










